// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtKA2DqvO13xRdFr3rGh3kj0tAjDHx6Js',
    appId: '1:518137228236:web:3be76cf6d65aa6f46d8b69',
    messagingSenderId: '518137228236',
    projectId: 'omar-hossam-fathey',
    authDomain: 'omar-hossam-fathey.firebaseapp.com',
    storageBucket: 'omar-hossam-fathey.appspot.com',
    measurementId: 'G-QQ8MZEYRSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANu1_uX-rdDKIoiOltdBIofb4HDzqt9uc',
    appId: '1:518137228236:android:d6f7e8e54688da5b6d8b69',
    messagingSenderId: '518137228236',
    projectId: 'omar-hossam-fathey',
    storageBucket: 'omar-hossam-fathey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClP9K9hn29LZhBagh5ccjRQXZP441z3D8',
    appId: '1:518137228236:ios:94faab4aeb6affb86d8b69',
    messagingSenderId: '518137228236',
    projectId: 'omar-hossam-fathey',
    storageBucket: 'omar-hossam-fathey.appspot.com',
    iosBundleId: 'com.example.omarHossamFathey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClP9K9hn29LZhBagh5ccjRQXZP441z3D8',
    appId: '1:518137228236:ios:94faab4aeb6affb86d8b69',
    messagingSenderId: '518137228236',
    projectId: 'omar-hossam-fathey',
    storageBucket: 'omar-hossam-fathey.appspot.com',
    iosBundleId: 'com.example.omarHossamFathey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtKA2DqvO13xRdFr3rGh3kj0tAjDHx6Js',
    appId: '1:518137228236:web:1053add75a378e486d8b69',
    messagingSenderId: '518137228236',
    projectId: 'omar-hossam-fathey',
    authDomain: 'omar-hossam-fathey.firebaseapp.com',
    storageBucket: 'omar-hossam-fathey.appspot.com',
    measurementId: 'G-X1PCXV7TQ2',
  );
}
